language: cpp
compiler:
  - gcc
  - clang
before_script:
  - git clone https://github.com/ktxsoftware/koremake.git
  - git clone https://github.com/ktxsoftware/node_bin.git
script: node_bin/node-linux64 koremake/koremake.js --compile
